#!/usr/bin/env bash
# Write an overlay that turns on the built-in devnet equivocation mode for the
# listed validators of stand xp<N>. $1 = N, $2 = comma-separated indices.
set -euo pipefail
N=$1; IDXS=$2
XP="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# On a committee of four, one equivocation tombstone leaves three
# selection-visible validators, so the run exercises the committee-floor path
# (R-111/R-112) rather than equivocation itself. Same gate as genN.py.
if [ "$N" -lt 5 ] && [ "${XP_ALLOW_SMALL_BYZ:-}" != "1" ]; then
  echo "byz_overlay.sh: refusing at N=$N — a byzantine run needs a committee >= 5;" >&2
  echo "  set XP_ALLOW_SMALL_BYZ=1 if the committee-floor path is the point." >&2
  exit 2
fi
mkdir -p "$XP/out"
OUT="$XP/out/xp$N.byz.yml"
{
  echo "# GENERATED by scripts/xp/byz_overlay.sh — equivocation on: $IDXS"
  echo "services:"
  for i in ${IDXS//,/ }; do
    echo "  validator-$i:"
    echo "    environment:"
    echo "      FLUENT_DPOS_BYZANTINE: equivocate"
  done
} > "$OUT"
echo "$OUT"
