#!/usr/bin/env python3
"""Generate the local-dpos-smoke stand for an arbitrary N (genesis-baked).

Reproduces the argv of devnet/local-dpos-smoke/docker-compose.yml and
.dpos.yml at any validator count. Writes a pair of files into out/:
xp<N>.yml (phase 1 — sequencer plus cert-upstream followers) and
xp<N>.dpos.yml (phase 2 — --dpos). Its own docker project name (xp<N>) and its
own /24 (172.<20+N>.0.0), so it never collides with the default smoke stand.

usage: genN.py <N> [byz-indices]

reth metrics (`--metrics`) are on for every validator: the executor and slasher
counters live on that registry, not on the commonware endpoint.

Host ports: validator-0 RPC = 28000+N, full-node = 29000+N, validator i's reth
registry = 26000+N*100+i, its commonware registry = 27000+N*100+i.
"""
import sys, os
from pathlib import Path

HERE = Path(__file__).resolve().parent
SMOKE = HERE.parent.parent                       # devnet/local-dpos-smoke
OUT_DIR = HERE / "out"
OUT_DIR.mkdir(exist_ok=True)

N = int(sys.argv[1])
BYZ = [int(x) for x in (sys.argv[2].split(",") if len(sys.argv) > 2 and sys.argv[2] else [])]
OUT = str(OUT_DIR)
SUB = f"172.{20 + N}.0"
IP = lambda i: f"{SUB}.{10 + i}"
FULL_IP = f"{SUB}.60"
INIT_IP = f"{SUB}.5"
IMG = "fluent-dpos-smoke:local"

# A byzantine equivocator on a committee of four does not test equivocation. The
# tombstone takes the selection-visible population to three, and what happens at
# the next commit is a property of the CONTRACT, not of the consensus code the
# overlay is aimed at. Refuse below five unless the caller says that is the point.
if BYZ and N < 5 and os.environ.get("XP_ALLOW_SMALL_BYZ") != "1":
    sys.exit(
        f"genN.py: refusing a byzantine overlay at N={N}. One tombstone leaves three "
        f"selection-visible validators, which exercises the committee-floor path "
        f"(R-111/R-112) rather than equivocation. Use N>=5, or set "
        f"XP_ALLOW_SMALL_BYZ=1 if the floor path is what you are after."
    )
INTERVAL = os.environ.get("EPOCH_BLOCK_INTERVAL", "32")
ACT = os.environ.get("DPOS_ACTIVATION_BLOCK", str(int(INTERVAL) * 2))

head = f"""# GENERATED by scripts/xp/genN.py — a stand of {N} validators.
# Do not edit by hand; regenerate with `genN.py {N}`.
name: xp{N}
networks:
  xp-net:
    driver: bridge
    ipam:
      config:
        - subnet: {SUB}.0/24
services:
  genesis-init:
    image: {IMG}
    entrypoint: ["/usr/local/bin/genesis-bootstrap"]
    command:
      - full
      - --peers={N}
      - --bootstrappers=1
      - --output=/runtime
      - --contracts-dir=/contracts
      - --chain-id=2026
      - --validator-ips={",".join(IP(i) for i in range(N))}
    environment:
      EPOCH_BLOCK_INTERVAL: "{INTERVAL}"
      DPOS_ACTIVATION_BLOCK: "{ACT}"
    volumes:
      - runtime:/runtime
      - {SMOKE}/contracts:/contracts:ro
    networks:
      xp-net:
        ipv4_address: {INIT_IP}
"""

seq = f"""
  validator-0:
    image: {IMG}
    depends_on:
      genesis-init:
        condition: service_completed_successfully
    entrypoint: ["/usr/local/bin/fluent"]
    command:
      - node
      - --chain=/runtime/genesis-local.json
      - --validator
      - --validator.block-time=1s
      - --dpos.staking-config=/runtime/staking-reader.json
      - --builder.extradata=
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=eth,net,web3
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --p2p-secret-key=/runtime/v0-p2p-secret.hex
      - --port=30303
      - --datadir=/runtime/reth-data/v0
    volumes:
      - runtime:/runtime
    ports:
      - "{28000 + N}:8545"
    networks:
      xp-net:
        ipv4_address: {IP(0)}
    healthcheck:
      test:
        - "CMD-SHELL"
        - "curl -s -X POST -H 'Content-Type: application/json' --data '{{\\"jsonrpc\\":\\"2.0\\",\\"method\\":\\"eth_blockNumber\\",\\"params\\":[],\\"id\\":1}}' http://localhost:8545 | grep -q result"
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 5s
"""

def follower(i, name, ip, datadir, extra_ports=""):
    return f"""
  {name}:
    image: {IMG}
    depends_on:
      validator-0:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        exec /usr/local/bin/fluent node \\
          --chain=/runtime/genesis-local.json \\
          --cert-upstream=ws://{IP(0)}:8546 \\
          --dpos.staking-config=/runtime/staking-reader.json \\
          --builder.extradata= \\
          --http --http.addr=0.0.0.0 --http.port=8545 --http.api=eth,net,web3 \\
          --trusted-peers="$$(cat /runtime/v0-enode.txt)" \\
          --trusted-only \\
          --disable-discovery \\
          --datadir=/runtime/reth-data/{datadir}
    volumes:
      - runtime:/runtime
{extra_ports}    networks:
      xp-net:
        ipv4_address: {ip}
"""

body = head + seq
for i in range(1, N):
    body += follower(i, f"validator-{i}", IP(i), f"v{i}")
body += follower(None, "full-node", FULL_IP, "full-node",
                 f'    ports:\n      - "{29000 + N}:8545"\n')
body += "\nvolumes:\n  runtime: {}\n"
open(f"{OUT}/xp{N}.yml", "w").write(body)

# ---- phase 2 overlay ----
def dpos_cmd(i):
    byz = ("\n    environment:\n      FLUENT_DPOS_BYZANTINE: equivocate"
           if i in BYZ else "")
    peers = (f'--trusted-peers="$$(cat /runtime/v0-enode.txt)" \\\n'
             f'          --trusted-only \\\n          --disable-discovery'
             if i else "--p2p-secret-key=/runtime/v0-p2p-secret.hex \\\n          --port=30303")
    ws = ("--ws --ws.addr=0.0.0.0 --ws.port=8546 \\\n          " if i == 0 else "")
    return f"""
  validator-{i}:
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        exec /usr/local/bin/fluent node \\
          --chain=/runtime/genesis-local.json \\
          --datadir=/runtime/reth-data/v{i} \\
          --dpos \\
          --dpos.bls-key-path=/runtime/keys/validator-{i}/bls.hex \\
          --dpos.peer-key-path=/runtime/keys/validator-{i}/peer.hex \\
          --dpos.staking-config=/runtime/staking-reader.json \\
          --dpos.bootstrappers=/runtime/peers.json \\
          --dpos.dialable={IP(i)}:9000 \\
          --dpos.metrics-port=9100 \\
          --dpos.slasher-keystore-path=/runtime/keys/validator-{i}/slasher.json \\
          --dpos.slasher-keystore-password-file=/runtime/keys/validator-{i}/slasher.pwd \\
          --builder.extradata= \\
          --metrics=0.0.0.0:9001 \\
          --http --http.addr=0.0.0.0 --http.port=8545 --http.api=eth,net,web3 \\
          {ws}{peers}
    ports:
      - "{26000 + N * 100 + i}:9001"
      - "{27000 + N * 100 + i}:9100"{byz}
"""

ov = (f"# GENERATED by scripts/xp/genN.py — phase 2 (--dpos) for stand xp{N}.\n"
      f"# Byzantine (equivocate): {BYZ or 'none'}\nservices:")
for i in range(N):
    ov += dpos_cmd(i)
open(f"{OUT}/xp{N}.dpos.yml", "w").write(ov)
print(f"wrote {OUT}/xp{N}.yml and {OUT}/xp{N}.dpos.yml  (byz={BYZ}, "
      f"rpc v0=localhost:{28000+N}, full-node=localhost:{29000+N}, "
      f"reth-metrics v{{i}}=localhost:{26000+N*100}+i)")
