#!/usr/bin/env bash
# Generate the N-validator soak compose pair (gitignored), scaling the
# production-path topology past its hardcoded 6. ROOT FIX for the dialable-IP
# string-concat bug (`172.20.0.1$IDX`, production-path.dpos.yml:36, silently
# breaks at IDX 10): every IP here is `172.20.0.$((10+idx))` arithmetic.
#
# Usage: gen-soak-compose.sh N   →  writes
#   docker-compose.soak.gen.yml       (phase A: bare sequencer chain, N validators)
#   docker-compose.soak.dpos.gen.yml  (phase B: --dpos overlay, N validators)
# `--peers N` scales all Rust-side keys/IPs/shares/peers.json for free; only the
# compose YAML + bash node arrays needed generating (research §2).
set -euo pipefail
cd "$(dirname "$0")/.."

N="${1:?usage: gen-soak-compose.sh N [COMMITTEE_TARGET]}"
# Validators idx >= TARGET are SPARES for committee self-heal. They are NOT profiled: they
# boot in PHASE A as bare followers so they build a reth datadir synced PAST the runtime
# staking deploy + activation (a fresh-from-genesis spare would read the still-CODELESS
# runtime ChainConfig at genesis_hash → dpos.rs:742 ABI buffer-overrun → crash). case-soak
# STOPS the spares right before the --dpos cold-restart (so they add ZERO cold-restart cert-
# follow load — 13 simultaneous cert-followers froze the L2 executor; committee+L2 alone is
# fine) and RESUMES a spare on-demand at refill (`up -d --no-deps --force-recreate`), where
# its phase-A datadir is past the deploy → code-ful ChainConfig → normal bare→dpos cold-start.
# full-node depends on the last COMMITTEE validator (not a spare) so the committee-only
# cold-restart `up` list does not pull spares back in.
TARGET="${2:-$N}"
(( TARGET >= 4 && TARGET <= N )) || { echo "gen-soak-compose: bad COMMITTEE_TARGET=$TARGET (need 4..$N)"; exit 1; }
# Ceiling mirrors dpos.rs:931 launch-reject (MAX_COMMITTEE_SIZE=51); floor keeps
# INITIAL_F>=1 (D4). Validators occupy 172.20.0.10..(10+N-1); full-node at .250.
(( N >= 4 ))  || { echo "gen-soak-compose: N=$N < 4 (need INITIAL_F>=1; MIN_COMMITTEE math, D4)"; exit 1; }
(( N <= 51 )) || { echo "gen-soak-compose: N=$N > 51 (exceeds MAX_COMMITTEE_SIZE=51, dpos.rs:931)"; exit 1; }

BASE="docker-compose.soak.gen.yml"
DPOS="docker-compose.soak.dpos.gen.yml"
FULL_IP="172.20.0.250"
SEQ_IP="172.20.0.10"

# comma-joined validator IPs for genesis-init --validator-ips
ips=""; for ((i=0;i<N;i++)); do ips+="172.20.0.$((10+i)),"; done; ips="${ips%,}"

# ── Phase A base ──────────────────────────────────────────────────────────
cat >"$BASE" <<EOF
name: fluent-dpos-soak
# GENERATED by gen-soak-compose.sh N=$N — do not edit (gitignored).
networks:
  fluent-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

x-fluent-build: &fluent-build
  build:
    context: ../..
    dockerfile: devnet/local-dpos-smoke/Dockerfile
  image: fluent-dpos-smoke:local

x-cpu-limit: &cpu-limit
  deploy:
    resources:
      limits:
        cpus: "2.0"

x-follower-health: &follower-health
  healthcheck:
    test:
      - "CMD-SHELL"
      - "curl -s -X POST -H 'Content-Type: application/json' --data '{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}' http://localhost:8545 | grep -q result"
    interval: 2s
    timeout: 2s
    retries: 30
    start_period: 5s

services:
  genesis-init:
    <<: *fluent-build
    entrypoint: ["/usr/local/bin/genesis-bootstrap"]
    command:
      - bare
      - --peers=$N
      - --bootstrappers=2
      - --output=/runtime
      - --chain-id=2026
      - --validator-ips=$ips
      # Transfer-free deployer prefix (fund-spammer/token/verifier/DeployStaking) → the
      # staking/chainConfig/liveness proxy CREATEs land one nonce earlier than the
      # production-path 8,14,18 (which has a pre-deploy BLEND transfer at nonce 3).
      - --staking-reader-create-nonces=7,13,17
    volumes:
      - runtime:/runtime
    networks:
      fluent-net:
        ipv4_address: 172.20.0.5

  validator-0:
    <<: [*fluent-build, *cpu-limit, *follower-health]
    depends_on:
      genesis-init:
        condition: service_completed_successfully
    entrypoint: ["/usr/local/bin/fluent"]
    command:
      - node
      - --chain=/runtime/genesis-local.json
      - --validator
      - --validator.block-time=1s
      - --dpos.staking-config=/runtime/staking-reader.json
      - --builder.extradata=
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=eth,net,web3
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --p2p-secret-key=/runtime/v0-p2p-secret.hex
      - --port=30303
      - --datadir=/runtime/reth-data/v0
    volumes:
      - runtime:/runtime
    ports:
      - "8545:8545"
      - "8546:8546"
    networks:
      fluent-net:
        ipv4_address: $SEQ_IP
EOF

# validators 1..N-1 (phase A followers of v0 via WS), staggered depends_on chain
for ((i=1;i<N;i++)); do
  prev=$((i-1))
  cat >>"$BASE" <<EOF

  validator-$i:
    <<: [*fluent-build, *cpu-limit, *follower-health]
    depends_on:
      validator-$prev:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        exec /usr/local/bin/fluent node \\
          --chain=/runtime/genesis-local.json \\
          --sequencer-url=ws://$SEQ_IP:8546 \\
          --dpos.staking-config=/runtime/staking-reader.json \\
          --builder.extradata= \\
          --http --http.addr=0.0.0.0 --http.port=8545 --http.api=eth,net,web3 \\
          --trusted-peers="\$(cat /runtime/v0-enode.txt)" \\
          --trusted-only \\
          --disable-discovery \\
          --datadir=/runtime/reth-data/v$i
    volumes:
      - runtime:/runtime
    networks:
      fluent-net:
        ipv4_address: 172.20.0.$((10+i))
EOF
done

# full-node follower
cat >>"$BASE" <<EOF

  full-node:
    <<: [*fluent-build, *cpu-limit, *follower-health]
    depends_on:
      validator-$((TARGET-1)):
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        exec /usr/local/bin/fluent node \\
          --chain=/runtime/genesis-local.json \\
          --sequencer-url=ws://$SEQ_IP:8546 \\
          --dpos.staking-config=/runtime/staking-reader.json \\
          --builder.extradata= \\
          --rpc.eth-proof-window=50000 \\
          --http --http.addr=0.0.0.0 --http.port=8545 --http.api=eth,net,web3 \\
          --trusted-peers="\$(cat /runtime/v0-enode.txt)" \\
          --trusted-only \\
          --disable-discovery \\
          --datadir=/runtime/reth-data/full-node
    volumes:
      - runtime:/runtime
    ports:
      - "18545:8545"
    networks:
      fluent-net:
        ipv4_address: $FULL_IP

volumes:
  runtime: {}
EOF

# ── Phase B --dpos overlay ────────────────────────────────────────────────
# NOTE: uses --dpos.bls-key-path (plaintext) — the working production-path key
# path. P4 (encrypted beacon shares via --dpos.bls-keystore-path) is NOT enabled:
# that flag is mutually-exclusive with bls-key-path and REQUIRES an EIP-2335 bls
# keystore + password the smoke genesis-bootstrap does not emit (enabling it would
# need a genesis-bootstrap change → violates D7). Shares persist plaintext-0600
# (fine for a devnet soak). See implementer report.
cat >"$DPOS" <<EOF
# GENERATED by gen-soak-compose.sh N=$N — phase B --dpos overlay (gitignored).
services:
  validator-0:
    command:
      - node
      - --chain=/runtime/genesis-local.json
      - --datadir=/runtime/reth-data/v0
      - --dpos
      - --dpos.follower-upstream=ws://172.20.0.11:8546
      - --dpos.bls-key-path=/runtime/keys/validator-0/bls.hex
      - --dpos.peer-key-path=/runtime/keys/validator-0/peer.hex
      - --dpos.staking-config=/runtime/staking-reader.json
      - --dpos.bootstrappers=/runtime/peers.json
      - --dpos.dialable=$SEQ_IP:9000
      - --dpos.metrics-port=9100
      - --dpos.slasher-keystore-path=/runtime/keys/validator-0/slasher.json
      - --dpos.slasher-keystore-password-file=/runtime/keys/validator-0/slasher.pwd
      - --builder.extradata=
      - --p2p-secret-key=/runtime/v0-p2p-secret.hex
      - --port=30303
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=eth,net,web3
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
    ports:
      - "19100:9100"
EOF

for ((i=1;i<N;i++)); do
  cat >>"$DPOS" <<EOF

  validator-$i:
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        exec /usr/local/bin/fluent node \\
          --chain=/runtime/genesis-local.json \\
          --datadir=/runtime/reth-data/v$i \\
          --dpos \\
          --dpos.follower-upstream=ws://$SEQ_IP:8546 \\
          --dpos.bls-key-path=/runtime/keys/validator-$i/bls.hex \\
          --dpos.peer-key-path=/runtime/keys/validator-$i/peer.hex \\
          --dpos.staking-config=/runtime/staking-reader.json \\
          --dpos.bootstrappers=/runtime/peers.json \\
          --dpos.dialable=172.20.0.$((10+i)):9000 \\
          --dpos.metrics-port=9100 \\
          --dpos.slasher-keystore-path=/runtime/keys/validator-$i/slasher.json \\
          --dpos.slasher-keystore-password-file=/runtime/keys/validator-$i/slasher.pwd \\
          --builder.extradata= \\
          --http --http.addr=0.0.0.0 --http.port=8545 --http.api=eth,net,web3 \\
          --ws --ws.addr=0.0.0.0 --ws.port=8546 \\
          --trusted-peers="\$(cat /runtime/v0-enode.txt)" \\
          --trusted-only \\
          --disable-discovery
EOF
done

cat >>"$DPOS" <<EOF

  full-node:
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        exec /usr/local/bin/fluent node \\
          --chain=/runtime/genesis-local.json \\
          --cert-follow \\
          --sequencer-url=ws://$SEQ_IP:8546 \\
          --dpos.staking-config=/runtime/staking-reader.json \\
          --builder.extradata= \\
          --rpc.eth-proof-window=50000 \\
          --http --http.addr=0.0.0.0 --http.port=8545 --http.api=eth,net,web3,admin \\
          --ws --ws.addr=0.0.0.0 --ws.port=8546 \\
          --trusted-peers="\$(cat /runtime/v0-enode.txt)" \\
          --trusted-only \\
          --disable-discovery \\
          --datadir=/runtime/reth-data/full-node
EOF

# ── L3 cascade follower (downstream): tier-3 of the multi-tier topology. Its ONLY
# upstream is L2 (full-node) — cert-follow over L2's consensus WS + devp2p pinned to
# L2's enode (/runtime/l2-enode.txt, written at runtime by soak_start_cascade_l3).
# --trusted-only + --disable-discovery ⇒ it can reach NOTHING but L2 (no validator
# access), exercising "followers serve followers" (docker-compose.cert-cascade.yml).
# Defined ONLY in the --dpos overlay (no certs exist in phase A) + started manually
# after the L2 enode is captured, so NO depends_on. L3 keeps --trusted-only and pins
# ONLY L2's enode — so it reaches NOTHING but L2 (consensus via L2's WS, EL bodies via
# L2 devp2p). L2 keeps --trusted-only too (its v0 backfill needs it); soak_start_cascade_l3
# makes L2 ACCEPT this inbound by admin_addTrustedPeer(L3-enode) at runtime (so neither
# tier weakens --trusted-only). admin is enabled here to read L3's own enode.
cat >>"$DPOS" <<EOF

  downstream:
    image: fluent-dpos-smoke:local
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        exec /usr/local/bin/fluent node \\
          --chain=/runtime/genesis-local.json \\
          --cert-follow \\
          --sequencer-url=ws://$FULL_IP:8546 \\
          --dpos.staking-config=/runtime/staking-reader.json \\
          --builder.extradata= \\
          --rpc.eth-proof-window=50000 \\
          --http --http.addr=0.0.0.0 --http.port=8545 --http.api=eth,net,web3,admin \\
          --trusted-peers="\$(cat /runtime/l2-enode.txt)" \\
          --trusted-only \\
          --disable-discovery \\
          --datadir=/runtime/reth-data/downstream
    volumes:
      - runtime:/runtime
    networks:
      fluent-net:
        ipv4_address: 172.20.0.251
    ports:
      - "28545:8545"
EOF

echo "generated $BASE + $DPOS for N=$N (validators 172.20.0.10..$((10+N-1)), full-node $FULL_IP)"
