// SPDX-License-Identifier: MIT
// This file is auto-generated
// DO NOT EDIT THIS FILE MANUALLY!
// Source contract: Router
// Generated at: 2024-12-06 15:49:26

pragma solidity ^0.8.0;


interface IRouter {
    struct Point {
        uint64 x;
        uint256 y;
    }

    function greeting(string calldata message) external returns (string memory _0);
    function customGreeting(string calldata message) external returns (string memory _0);
    function complex(Point memory point) external returns (Point memory _0);
}
