// SPDX-License-Identifier: MIT
// This file is auto-generated
// DO NOT EDIT THIS FILE MANUALLY!
// Source contract: ROUTER
// Generated at: 2024-12-05 22:31:51

pragma solidity ^0.8.0;

interface IRouter {
    function greeting(string memory message) external returns (string memory);
    function customGreeting(string memory message) external returns (string memory);
}
