"""test_compose_parity.py — pin compose_gen's per-service command against the BASH ORACLE.

The generator-fidelity guard the v61.7 downstream-crash class asked for: parse BOTH the
Python-generated compose pair AND a checked-in fixture derived from a real v60 bundle
(soak-out/bundle-20260720T170507Z, generated by gen-soak-compose.sh), then assert
entrypoint/command/environment equality PER SERVICE — across every service, not just the L3
downstream, so any command-line divergence (a stray/renamed flag, an empty-value arg) trips a
test the round it lands instead of a container the round after.

Oracle: dpos_harness/tests/fixtures/v60-compose/v60-{base,dpos}.compose.yml — the bundle's two
compose files copied verbatim (renamed only to dodge the `docker-compose.sim*.gen.yml`
gitignore so they check in; no logs). The bundle's knobs: N=14, COMMITTEE_TARGET=10,
IDENTITY_POOL=20, SIM_GEO_LATENCY=1, PEER_HOST_MODE=ip, BOOTSTRAP_MODE=json, prune=full.

Normalization (semantically-neutral, documented): we compare ONLY entrypoint/command/environment
per service via yaml.safe_load, which
  - drops YAML comments and key ORDER (both differ harmlessly: the bash carries prose comments
    the port omits, and mappings are order-insensitive here);
  - RESOLVES the `<<` merge anchors, so a validator's `environment` (carried by *fluent-build)
    is compared as the resolved {RUST_LOG_STYLE: never}, identically on both sides;
  - never looks at the top-level `volumes:` stanza — the one place SIM_DATA_ROOT rewrites (a
    deployment-fact knob outside every service's command) — so the fixture's bind-mount device
    line and the test's default `runtime: {}` are both irrelevant to this per-service oracle.
Command block scalars are compared byte-for-byte (list-of-one-string), which is the whole point:
the fluent argv (incl. any tc-netem prologue) must be identical to what bash emits.
"""

import os

import pytest
import yaml

from dpos_harness.stack import compose_gen

_FIXDIR = os.path.join(os.path.dirname(__file__), "fixtures", "v60-compose")

# The exact knobs soak-out/bundle-20260720T170507Z was generated with (see module docstring).
_N, _TARGET, _POOL = 14, 10, 20
_CMD_FIELDS = ("entrypoint", "command", "environment")


def _load(path):
    with open(path) as f:
        return yaml.safe_load(f)


def _fields(svc):
    """The per-service command surface this oracle pins."""
    return {k: svc.get(k) for k in _CMD_FIELDS}


@pytest.fixture(scope="module")
def py_services(tmp_path_factory):
    """Generate the Python compose pair at the bundle's knobs and return {file: services-dict}.
    SIM_GEO_LATENCY=1 matches the bundle; SIM_DATA_ROOT is intentionally left unset (it would
    trigger a real makedirs and only rewrites top-level volumes, which this oracle ignores)."""
    out = str(tmp_path_factory.mktemp("pygen"))
    prev = os.environ.get("SIM_GEO_LATENCY")
    os.environ["SIM_GEO_LATENCY"] = "1"
    try:
        base, dpos = compose_gen.generate(_N, target=_TARGET, identity_pool=_POOL, out_dir=out)
    finally:
        if prev is None:
            os.environ.pop("SIM_GEO_LATENCY", None)
        else:
            os.environ["SIM_GEO_LATENCY"] = prev
    return {"base": _load(base)["services"], "dpos": _load(dpos)["services"]}


_BASH_BASE = _load(os.path.join(_FIXDIR, "v60-base.compose.yml"))["services"]
_BASH_DPOS = _load(os.path.join(_FIXDIR, "v60-dpos.compose.yml"))["services"]


def test_base_service_set_matches_oracle(py_services):
    """Phase-A service SET equality: no EXTRA services in the Python output (the phantom
    validator-14..17 class) and none MISSING vs the v60 bash fixture."""
    py, bash = set(py_services["base"]), set(_BASH_BASE)
    assert py - bash == set(), f"extra (phantom) services: {sorted(py - bash)}"
    assert bash - py == set(), f"missing services: {sorted(bash - py)}"
    assert py == bash


def test_dpos_service_set_matches_oracle(py_services):
    """Phase-B --dpos overlay service SET equality — same no-extras / no-missing guard."""
    py, bash = set(py_services["dpos"]), set(_BASH_DPOS)
    assert py - bash == set(), f"extra (phantom) services: {sorted(py - bash)}"
    assert bash - py == set(), f"missing services: {sorted(bash - py)}"
    assert py == bash


@pytest.mark.parametrize("name", sorted(_BASH_BASE))
def test_base_service_command_parity(name, py_services):
    """Phase-A: every service's entrypoint/command/environment matches the bash oracle."""
    assert _fields(py_services["base"][name]) == _fields(_BASH_BASE[name])


@pytest.mark.parametrize("name", sorted(_BASH_DPOS))
def test_dpos_service_command_parity(name, py_services):
    """Phase-B --dpos overlay: same per-service command parity (incl. the L3 `downstream`)."""
    assert _fields(py_services["dpos"][name]) == _fields(_BASH_DPOS[name])


# ── the host-port publish mapping ────────────────────────────────────────────────────
# Which services publish which host ports IS the validator-0 asymmetry, and the readers act on
# it: `nodes.node_metrics` scrapes :19100/:19200 over the host, bring-up reads heads over
# :8545/:18545/:28545, and everything else goes through `docker compose exec`. The generator
# emits these stanzas from topology.HOST_RPC_PORTS / HOST_METRICS_PORTS, so this oracle is what
# turns a map edit into a failing test: publish a port the readers do not expect (or stop
# publishing one they do) and the compose file diverges from the bash bundle here.

@pytest.mark.parametrize("name", sorted(_BASH_BASE))
def test_base_service_ports_match_oracle(name, py_services):
    """Phase-A: per-service `ports:` equality — v0's 8545/8546, the full-node's 18545, and
    NOTHING for validator-1..N (a published committee node would be an extra list here)."""
    assert py_services["base"][name].get("ports") == _BASH_BASE[name].get("ports")


@pytest.mark.parametrize("name", sorted(_BASH_DPOS))
def test_dpos_service_ports_match_oracle(name, py_services):
    """Phase-B overlay: v0's metrics 19100/19200 and the L3 downstream's 28545, no other."""
    assert py_services["dpos"][name].get("ports") == _BASH_DPOS[name].get("ports")


def test_the_published_ports_are_exactly_the_topology_maps(py_services):
    """The two views agree: every mapping in the generated compose is one the topology maps
    claim, and every claim is published. Without this, ADDING a service to a map is invisible —
    the per-service parity tests only compare services the bash oracle already knows."""
    from dpos_harness.core import topology as t
    published = {}
    for group in ("base", "dpos"):          # v0 publishes in BOTH: RPC/WS here, metrics there
        for svc, fields in py_services[group].items():
            if fields.get("ports"):
                published.setdefault(svc, []).extend(fields["ports"])
    assert published == {
        t.PINNED_RPC_HOST: [t.host_rpc_publish(t.PINNED_RPC_HOST),
                            f"{t.HOST_WS_PORT}:{t.WS_PORT}",
                            *t.host_metrics_publish(t.PINNED_RPC_HOST)],
        t.FULL_NODE: [t.host_rpc_publish(t.FULL_NODE)],
        t.DOWNSTREAM: [t.host_rpc_publish(t.DOWNSTREAM)],
    }
    assert set(t.HOST_RPC_PORTS) | set(t.HOST_METRICS_PORTS) == set(published)


def test_downstream_trusted_peers_is_well_formed(py_services):
    """Guard the exact v61.7 crash SHAPE at the generator level: the downstream command must pass
    a NON-EMPTY-id enode file to --trusted-peers (`$(cat /runtime/l2-enode.txt)`), never an inline
    `enode://@…`. The malformed *value* is written at runtime (bringup._start_cascade_l3, covered
    in test_bringup), but the command TEMPLATE must reference the file, not embed a literal id."""
    cmd = "\n".join(py_services["dpos"]["downstream"]["command"])
    assert '--trusted-peers="$(cat /runtime/l2-enode.txt)"' in cmd
    assert "enode://@" not in cmd
