use fluentbase_sdk::derive::{derive_evm_error, derive_keccak256_id};

pub const ERR_UNKNOWN: u32 = derive_evm_error!("Unknown()");
pub const ERR_MALFORMED_INPUT: u32 = derive_evm_error!("MalformedInput()");
pub const ERR_INSUFFICIENT_BALANCE: u32 = derive_evm_error!("InsufficientBalance()");
pub const ERR_INSUFFICIENT_ALLOWANCE: u32 = derive_evm_error!("InsufficientAllowance()");
pub const ERR_INDEX_OUT_OF_BOUNDS: u32 = derive_evm_error!("IndexOutOfBounds()");
pub const ERR_DECODE: u32 = derive_evm_error!("DecodeError()");
pub const ERR_INVALID_META_NAME: u32 = derive_evm_error!("InvalidMetaName()");
pub const ERR_INVALID_META_SYMBOL: u32 = derive_evm_error!("InvalidMetaSymbol()");
pub const ERR_MINTABLE_PLUGIN_NOT_ACTIVE: u32 = derive_evm_error!("MintablePluginNotActive()");
pub const ERR_PAUSABLE_PLUGIN_NOT_ACTIVE: u32 = derive_evm_error!("PausablePluginNotActive()");
pub const ERR_ALREADY_PAUSED: u32 = derive_evm_error!("AlreadyPaused()");
pub const ERR_ALREADY_UNPAUSED: u32 = derive_evm_error!("AlreadyUnpaused()");
pub const ERR_INVALID_MINTER: u32 = derive_evm_error!("InvalidMinter()");
pub const ERR_INVALID_PAUSER: u32 = derive_evm_error!("InvalidPauser()");
pub const ERR_INVALID_RECIPIENT: u32 = derive_evm_error!("InvalidRecipient()");
pub const ERR_OVERFLOW: u32 = derive_evm_error!("Overflow()");
pub const ERR_VALIDATION: u32 = derive_evm_error!("Validation()");
pub const ERR_UNINIT: u32 = derive_evm_error!("UninitError()");
pub const ERR_CONVERSION: u32 = derive_evm_error!("ConversionError()");

pub const SIG_SYMBOL: u32 = derive_keccak256_id!("symbol()");
pub const SIG_NAME: u32 = derive_keccak256_id!("name()");
pub const SIG_DECIMALS: u32 = derive_keccak256_id!("decimals()");
pub const SIG_TOTAL_SUPPLY: u32 = derive_keccak256_id!("totalSupply()");
pub const SIG_BALANCE: u32 = derive_keccak256_id!("balance()");
pub const SIG_BALANCE_OF: u32 = derive_keccak256_id!("balanceOf(address)");
pub const SIG_TRANSFER: u32 = derive_keccak256_id!("transfer(address,uint256)");
pub const SIG_TRANSFER_FROM: u32 = derive_keccak256_id!("transferFrom(address,address,uint256)");
pub const SIG_ALLOWANCE: u32 = derive_keccak256_id!("allowance(address)");
pub const SIG_APPROVE: u32 = derive_keccak256_id!("approve(address,uint256)");
pub const SIG_MINT: u32 = derive_keccak256_id!("mint(address,uint256)");
pub const SIG_PAUSE: u32 = derive_keccak256_id!("pause()");
pub const SIG_UNPAUSE: u32 = derive_keccak256_id!("unpause()");
pub const SIG_TOKEN2022: u32 = derive_keccak256_id!("token2022()");
