use crate::{svm_core::macros::*, test_interpreter_and_jit_asm};
use alloc::{format, sync::Arc, vec, vec::Vec};
use solana_rbpf::{
    assembler::assemble,
    elf::Executable,
    error::ProgramResult,
    program::{BuiltinProgram, FunctionRegistry, SBPFVersion},
    static_analysis::Analysis,
    vm::{Config, TestContextObject},
};

pub fn example_asm(source: &str) -> Vec<u8> {
    let loader = Arc::new(BuiltinProgram::new_loader(
        Config {
            enable_symbol_and_section_labels: true,
            ..Config::default()
        },
        FunctionRegistry::default(),
    ));

    let executable = assemble::<TestContextObject>(source, loader).unwrap();

    let (_, bytecode) = executable.get_text_bytes();

    bytecode.to_vec()
}

// pub fn example_disasm_from_bytes(program: &[u8]) {
//     let loader = Arc::new(BuiltinProgram::new_mock());
//     let executable = Executable::<TestContextObject>::from_text_bytes(
//         program,
//         loader,
//         SBPFVersion::V2,
//         FunctionRegistry::default(),
//     )
//         .unwrap();
//     let analysis = Analysis::from_executable(&executable).unwrap();
//     let stdout = std::io::stdout();
//     analysis.disassemble(&mut stdout.lock()).unwrap();
// }

pub fn example_mov() {
    test_interpreter_and_jit_asm!(
        "
        mov32 r1, 1
        mov32 r0, r1
        exit",
        [],
        (),
        TestContextObject::new(3),
        ProgramResult::Ok(0x1),
    );
}

pub fn example_add32() {
    test_interpreter_and_jit_asm!(
        "
        mov32 r0, 0
        mov32 r1, 2
        add32 r0, 1
        add32 r0, r1
        exit",
        [],
        (),
        TestContextObject::new(5),
        ProgramResult::Ok(0x3),
    );
}

// fn gen_add_bytecode() {
//     let bytecode = example_asm(
//         "
//     entrypoint:
//         ldxdw r2, [r1+0x00]
//         ldxdw r3, [r1+0x08]
//         add   r2, r3
//         stxdw [r1+0x10], r2
//     l_exit:
//         exit",
//     );
//
//     println!("Generated bytecode (hex): {:x?}", &bytecode);
// }
