// mod exec;

use crate::svm_core::helpers::SvmTransactResult;
use core::fmt::Error;

pub fn svm_transact<T>(
    storage: &mut T,
    // checked_tx: Checked<Tx>,
    // header: &'a PartialBlockHeader,
    // coinbase_contract_id: ContractId,
    // gas_price: Word,
    // memory: &'a mut MemoryInstance,
    // consensus_params: ConsensusParameters,
    // extra_tx_checks: bool,
    // execution_data: &mut ExecutionData,
) -> core::result::Result<SvmTransactResult, Error>
// where
//     Tx: ExecutableTransaction + Cacheable + Send + Sync + 'static,
//     <Tx as IntoChecked>::Metadata: CheckedMetadata + Send + Sync,
//     T: KeyValueInspect<Column = Column>,
{
    // let execution_options = ExecutionOptions {
    //     extra_tx_checks,
    //     backtrace: false,
    // };
    //
    // let block_executor =
    //     BlockExecutor::new(WasmRelayer {}, execution_options.clone(), consensus_params)
    //         .expect("failed to create block executor");
    //
    // let structured_storage =
    //     StructuredStorage::new(storage);
    // let mut structured_storage =
    //     structured_storage.into_transaction();
    // let in_memory_transaction =
    //     InMemoryTransaction::new(
    //     Changes::new(),
    //     ConflictPolicy::Overwrite,
    //     &mut structured_storage,
    // );
    // let tx_transaction =
    //     &mut TxStorageTransaction::new(in_memory_transaction);
    //
    // let tx_id = checked_tx.id();
    //
    // let mut checked_tx = checked_tx;
    // if execution_options.extra_tx_checks {
    //     checked_tx = block_executor.extra_tx_checks(checked_tx, header, tx_transaction, memory)?;
    // }

    // Here we go to solana way...

    // test_interpreter_and_jit_asm!(
    //     "
    //     mov32 r1, 1
    //     mov32 r0, r1
    //     exit",
    //     [],
    //     (),
    //     TestContextObject::new(3),
    //     ProgramResult::Ok(0x1),
    // );

    // let bytecode = example_asm(
    //     "
    // entrypoint:
    //     ldxdw r2, [r1+0x00]
    //     ldxdw r3, [r1+0x08]
    //     add   r2, r3
    //     stxdw [r1+0x10], r3
    // l_exit:
    //     exit",
    // );
    //
    // println!("\n::Generated bytecode:");
    // for (i, byte) in bytecode.iter().enumerate() {
    //     print!("{:#04x} ", byte);
    // }
    //
    // println!("\n::Disasm:");
    // let program: &'static [u8] = &[
    //     0x79, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x79, 0x13, 0x08, 0x00, 0x00, 0x00, 0x00,
    //     0x00, 0x0f, 0x32, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7b, 0x21, 0x10, 0x00, 0x00, 0x00,
    //     0x00, 0x00, 0x95, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    // ];
    // example_disasm_from_bytes(program);
    //
    // let mut svm_memory: Vec<u8> = vec![0; 1024 * 1024]; // 1 MB memory
    //
    // // Initialize some values in memory for testing
    // svm_memory[0x00..0x08].copy_from_slice(&[0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]); //
    // Example value 1 svm_memory[0x08..0x10].copy_from_slice(&[0x02, 0x00, 0x00, 0x00, 0x00,
    // 0x00, 0x00, 0x00]); // Example value 2
    //
    // // if let Some(updated_memory) = execute_generated_program(program, &mut svm_memory) {
    // //     println!("Program executed successfully.");
    // //     println!("Memory content after execution:");
    // //     for (i, byte) in updated_memory.iter().enumerate().take(32) {
    // //         // Display first bytes for example
    // //         println!("Byte {}: {:#04x}", i, byte);
    // //     }
    // // } else {
    // //     println!("Program execution failed.");
    // // }
    //
    // example_mov();
    // example_add32();
    // // test_struct_func_pointer();
    // // example_syscall();
    //
    // // ----------
    // let reverted = false;
    // // let (reverted, program_state, tx, receipts) =
    // //     block_executor.attempt_tx_execution_with_vm(
    // //         checked_tx,
    // //         header,
    // //         coinbase_contract_id,
    // //         gas_price,
    // //         tx_transaction,
    // //         memory,
    // //     )?;
    // //
    // // block_executor.spend_input_utxos(tx.inputs(), tx_transaction, reverted, execution_data)?;
    // //
    // // block_executor.persist_output_utxos(
    // //     *header.height(),
    // //     execution_data,
    // //     &tx_id,
    // //     tx_transaction,
    // //     tx.inputs(),
    // //     tx.outputs(),
    // // )?;
    //
    // // tx_st_transaction
    // //     .storage::<ProcessedTransactions>()
    // //     .insert(&tx_id, &());
    //
    // // block_executor.update_execution_data(
    // //     &tx,
    // //     execution_data,
    // //     receipts.clone(),
    // //     gas_price,
    // //     reverted,
    // //     program_state,
    // //     tx_id,
    // // )?;

    Ok(SvmTransactResult {
        reverted: false,
        // program_state,
        // tx,
        // receipts,
        // changes: tx_transaction.changes().clone(),
    })
}

pub fn svm_transact_commit<T>(
    storage: &mut T,
    // checked_tx: Checked<Tx>,
    // header: &PartialBlockHeader,
    // coinbase_contract_id: ContractId,
    // gas_price: Word,
    // consensus_params: ConsensusParameters,
    // extra_tx_checks: bool,
    // execution_data: &mut ExecutionData,
) -> Result<SvmTransactResult, Error>
// where
//     Tx: ExecutableTransaction + Cacheable + Send + Sync + 'static,
//     <Tx as IntoChecked>::Metadata: CheckedMetadata + Send + Sync,
//     T: KeyValueMutate<Column = Column>,
{
    // debug_log!("ecl(svm_transact_commit): start");

    // TODO warmup storage from state based on tx inputs?
    // let inputs = checked_tx.transaction().inputs();
    // for input in inputs {
    //     match input {
    //         Input::CoinSigned(v) => {}
    //         Input::CoinPredicate(v) => {}
    //         Input::Contract(v) => {}
    //         Input::MessageCoinSigned(v) => {}
    //         Input::MessageCoinPredicate(v) => {}
    //         Input::MessageDataSigned(v) => {}
    //         Input::MessageDataPredicate(v) => {}
    //     }
    // }

    // let mut memory = MemoryInstance::new();

    let result = svm_transact(
        storage,
        // checked_tx,
        // header,
        // coinbase_contract_id,
        // gas_price,
        // &mut memory,
        // consensus_params,
        // extra_tx_checks,
        // execution_data,
    )?;

    // for (col_num, changes) in &result.changes {
    //     let column: Column = col_num.clone().try_into().expect("valid column number");
    //     match column {
    //         Column::Metadata
    //         | Column::ContractsRawCode
    //         | Column::ContractsState
    //         | Column::ContractsLatestUtxo
    //         | Column::ContractsAssets
    //         | Column::ContractsAssetsMerkleData
    //         | Column::ContractsAssetsMerkleMetadata
    //         | Column::ContractsStateMerkleData
    //         | Column::ContractsStateMerkleMetadata
    //         | Column::Coins => {
    //             for (key, op) in changes {
    //                 match op {
    //                     WriteOperation::Insert(v) => {
    //                         storage.write(key, column, v)?;
    //                     }
    //                     WriteOperation::Remove => {
    //                         storage.delete(key, column)?;
    //                     }
    //                 }
    //             }
    //         }
    //
    //         Column::Transactions
    //         | Column::FuelBlocks
    //         | Column::FuelBlockMerkleData
    //         | Column::FuelBlockMerkleMetadata
    //         | Column::Messages
    //         | Column::ProcessedTransactions
    //         | Column::FuelBlockConsensus
    //         | Column::ConsensusParametersVersions
    //         | Column::StateTransitionBytecodeVersions
    //         | Column::UploadedBytecodes
    //         | Column::GenesisMetadata => {
    //             panic!("unsupported column {:?} operation", column)
    //         }
    //     }
    // }

    Ok(result)
}
