use crate::examples::example_asm;

#[test]
fn bytecode_translate_test() {
    let bytecode = example_asm(
        "
    entrypoint:
        ldxdw r2, [r1+0x00]
        ldxdw r3, [r1+0x08]
        add   r2, r3
        stxdw [r1+0x10], r3
    l_exit:
        exit",
    );

    println!("Generated bytecode (hex): {:x?}", &bytecode);
}
