//! Turns the corpus into Rust source.
//!
//! The corpus supplies Solidity type strings at runtime, so nothing a macro can act on. Generating
//! source before compilation lets `sol_to_rust` - the mapping the SDK's derive already uses - be
//! called as an ordinary function.

use fluentbase_sdk_derive_core::abi::types::{sol_to_rust, SolType};
use quote::quote;
use serde_json::Value;
use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    path::PathBuf,
};

fn main() {
    let corpus = PathBuf::from("vectors/contract-interface-abi2.json");
    println!("cargo:rerun-if-changed={}", corpus.display());
    println!("cargo:rerun-if-changed=build.rs");

    if !corpus.exists() {
        panic!("corpus not found at {corpus:?} - run `make vectors` first");
    }

    let entries: Vec<Value> =
        serde_json::from_str(&fs::read_to_string(&corpus).expect("read corpus")).expect("parse");

    // One probe per distinct signature: the vectors sharing a signature reuse the same
    // monomorphisation, which is what makes 1880 vectors cost 1425 instantiations.
    let mut by_signature: BTreeMap<String, Vec<&Value>> = BTreeMap::new();
    for entry in &entries {
        let signature = entry["types"]
            .as_str()
            .expect("types is a string")
            .to_string();
        by_signature.entry(signature).or_default().push(entry);
    }

    let mut out = String::from(
        "// generated by build.rs - do not edit\n\
         #[allow(unused_imports)]\n\
         use alloy_primitives::{aliases::*, Address, Signed, Uint};\n\
         #[allow(unused_imports)]\n\
         use codec_conformance::{Bytes, FixedBytes};\n\
         #[allow(unused_imports)]\n\
         use codec_conformance::{addr, b, check_vectors, fb, int, uint, Report, Vector};\n\n",
    );

    let mut bodies = String::new();
    let mut calls = String::new();

    for (index, (signature, vectors)) in by_signature.iter().enumerate() {
        let types: Vec<String> = serde_json::from_str(signature).expect("types is a JSON array");
        let sol_types: Vec<SolType> = types.iter().map(|t| parse_type(t)).collect();
        let rust_type = args_tuple(&sol_types);

        let mut rows = String::new();
        for vector in vectors {
            let name = vector["name"].as_str().expect("name");
            let values: Vec<Value> =
                serde_json::from_str(vector["values"].as_str().expect("values")).expect("values");
            let expected = vector["result"]
                .as_str()
                .expect("result")
                .trim_start_matches("0x");

            let parts: Vec<String> = sol_types
                .iter()
                .zip(&values)
                .map(|(t, v)| emit_value(t, v))
                .collect();
            let tuple = if parts.len() == 1 {
                format!("({},)", parts[0])
            } else {
                format!("({})", parts.join(", "))
            };

            rows.push_str(&format!("        ({name:?}, {tuple}, {expected:?}),\n"));
        }

        bodies.push_str(&format!(
            "// {signature}\nfn case_{index}(report: &mut Report) {{\n    let vectors: Vec<Vector<'_, {rust_type}>> = vec![\n{rows}    ];\n    check_vectors(report, vectors);\n}}\n\n"
        ));
        calls.push_str(&format!("    case_{index}(report);\n"));
    }

    out.push_str(&bodies);
    out.push_str(&format!(
        "pub fn tuple_path_cases(report: &mut Report) {{\n{calls}}}\n"
    ));

    // The derive path. `sol_to_rust` maps `tuple(...)` to an anonymous Rust tuple, so nothing above
    // reaches `#[derive(Codec)]` - and the largest defect found so far, an array striding by a
    // `HEADER_SIZE` that was neither head width nor inline width, lived there. Every
    // tuple node becomes a named struct instead, and only the signatures that contain one need a
    // second case.
    let mut shapes: BTreeSet<String> = BTreeSet::new();
    for signature in by_signature.keys() {
        let types: Vec<String> = serde_json::from_str(signature).expect("types");
        for t in &types {
            collect_shapes(&parse_type(t), &mut shapes);
        }
    }
    let names: BTreeMap<String, String> = shapes
        .iter()
        .enumerate()
        .map(|(i, shape)| (shape.clone(), format!("S{i}")))
        .collect();

    for (shape, name) in &names {
        let SolType::Tuple(members) = parse_type(shape) else {
            unreachable!("shapes are tuples")
        };
        let fields: Vec<String> = members
            .iter()
            .enumerate()
            .map(|(i, m)| format!("    f{i}: {},", rust_type_named(m, &names)))
            .collect();
        out.push_str(&format!(
            "#[derive(fluentbase_codec::Codec, Default, Debug, PartialEq, Clone)]\n\
             #[allow(dead_code)]\n\
             struct {name} {{\n{}\n}}\n\n",
            fields.join("\n")
        ));
    }

    let mut derive_bodies = String::new();
    let mut derive_calls = String::new();

    for (index, (signature, vectors)) in by_signature.iter().enumerate() {
        if !signature.contains("tuple(") {
            continue;
        }
        let types: Vec<String> = serde_json::from_str(signature).expect("types");
        let sol_types: Vec<SolType> = types.iter().map(|t| parse_type(t)).collect();

        let parts: Vec<String> = sol_types
            .iter()
            .map(|t| rust_type_named(t, &names))
            .collect();
        let rust_type = if parts.len() == 1 {
            format!("({},)", parts[0])
        } else {
            format!("({})", parts.join(", "))
        };

        let mut rows = String::new();
        for vector in vectors {
            let name = vector["name"].as_str().expect("name");
            let values: Vec<Value> =
                serde_json::from_str(vector["values"].as_str().expect("values")).expect("values");
            let expected = vector["result"]
                .as_str()
                .expect("result")
                .trim_start_matches("0x");

            let items: Vec<String> = sol_types
                .iter()
                .zip(&values)
                .map(|(t, v)| emit_value_named(t, v, &names))
                .collect();
            let tuple = if items.len() == 1 {
                format!("({},)", items[0])
            } else {
                format!("({})", items.join(", "))
            };
            rows.push_str(&format!("        ({name:?}, {tuple}, {expected:?}),\n"));
        }

        derive_bodies.push_str(&format!(
            "// derive: {signature}\nfn derive_case_{index}(report: &mut Report) {{\n    let vectors: Vec<Vector<'_, {rust_type}>> = vec![\n{rows}    ];\n    check_vectors(report, vectors);\n}}\n\n"
        ));
        derive_calls.push_str(&format!("    derive_case_{index}(report);\n"));
    }

    out.push_str(&derive_bodies);
    out.push_str(&format!(
        "pub fn derive_path_cases(report: &mut Report) {{\n{derive_calls}}}\n"
    ));

    let dest = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("cases.rs");
    fs::write(&dest, out).expect("write generated cases");

    println!(
        "cargo:warning=generated {} probes from {} vectors",
        by_signature.len(),
        entries.len()
    );
}

/// The Rust type of one vector's argument list: a tuple of its top-level types, matching what
/// `encode_function_args` takes.
fn args_tuple(types: &[SolType]) -> String {
    let parts: Vec<String> = types
        .iter()
        .map(|t| {
            let rust = sol_to_rust(t).unwrap_or_else(|e| panic!("{t:?}: {e:?}"));
            quote!(#rust).to_string()
        })
        .collect();

    // A one-element Rust tuple needs the trailing comma to stay a tuple.
    if parts.len() == 1 {
        format!("({},)", parts[0])
    } else {
        format!("({})", parts.join(", "))
    }
}

/// Parses a Solidity type string into `SolType`.
///
/// `derive-core` only has the other direction - `abi_type()` and `Display` both go `SolType ->
/// String` - so this is the piece the corpus needs and the codebase does not have.
fn parse_type(s: &str) -> SolType {
    let s = s.trim();

    if let Some(rest) = s.strip_suffix(']') {
        let (head, count) = rest.rsplit_once('[').expect("malformed array suffix");
        let inner = Box::new(parse_type(head));
        return if count.is_empty() {
            SolType::Array(inner)
        } else {
            SolType::FixedArray(inner, count.parse().expect("array length"))
        };
    }

    if let Some(body) = s.strip_prefix("tuple(").and_then(|b| b.strip_suffix(')')) {
        let members = if body.trim().is_empty() {
            Vec::new()
        } else {
            split_top_level(body)
                .iter()
                .map(|p| parse_type(p))
                .collect()
        };
        return SolType::Tuple(members);
    }

    match s {
        "address" => SolType::Address,
        "bool" => SolType::Bool,
        "string" => SolType::String,
        "bytes" => SolType::Bytes,
        // The corpus uses the canonical aliases 15 times each.
        "uint" => SolType::Uint(256),
        "int" => SolType::Int(256),
        _ => {
            if let Some(bits) = s.strip_prefix("uint") {
                SolType::Uint(bits.parse().expect("uint width"))
            } else if let Some(bits) = s.strip_prefix("int") {
                SolType::Int(bits.parse().expect("int width"))
            } else if let Some(size) = s.strip_prefix("bytes") {
                SolType::FixedBytes(size.parse().expect("bytes size"))
            } else {
                panic!("unsupported solidity type: {s}")
            }
        }
    }
}

/// Splits on commas at paren depth zero. The corpus nests to depth 7, so `split(',')` is wrong.
fn split_top_level(body: &str) -> Vec<String> {
    let mut parts = Vec::new();
    let mut depth = 0usize;
    let mut current = String::new();

    for ch in body.chars() {
        match ch {
            '(' => depth += 1,
            ')' => depth -= 1,
            ',' if depth == 0 => {
                parts.push(core::mem::take(&mut current));
                continue;
            }
            _ => {}
        }
        current.push(ch);
    }
    if !current.is_empty() {
        parts.push(current);
    }
    parts
}

/// Emits a Rust expression building one corpus value.
///
/// Driven by the type tree, not by the JSON tags: `address` and `string` both arrive tagged
/// `"string"`, and arrays arrive as bare JSON lists with no tag at all.
fn emit_value(ty: &SolType, v: &Value) -> String {
    match ty {
        SolType::Address => format!("addr({:?})", v["value"].as_str().expect("address")),
        SolType::String => format!("{:?}.to_string()", v["value"].as_str().expect("string")),
        SolType::Bytes => format!("b({:?})", v["value"].as_str().expect("bytes")),
        SolType::FixedBytes(n) => {
            format!("fb::<{n}>({:?})", v["value"].as_str().expect("fixed bytes"))
        }
        SolType::Bool => format!("{}", v["value"].as_bool().expect("bool")),
        SolType::Uint(bits) => emit_uint(*bits, v["value"].as_str().expect("uint")),
        SolType::Int(bits) => emit_int(*bits, v["value"].as_str().expect("int")),
        SolType::Array(inner) => {
            let items = emit_elements(inner, v);
            format!("vec![{}]", items.join(", "))
        }
        SolType::FixedArray(inner, _) => {
            let items = emit_elements(inner, v);
            format!("[{}]", items.join(", "))
        }
        SolType::Tuple(members) => {
            let values = v["value"].as_array().expect("tuple members");
            let mut items: Vec<String> = members
                .iter()
                .zip(values)
                .map(|(t, e)| emit_value(t, e))
                .collect();
            // Mirrors `to_rust_tuple`: a one-member tuple collapses only while the member is
            // static. A dynamic member keeps the tuple, because the tuple carries an offset word
            // the bare member does not.
            match items.len() {
                1 if !is_dynamic(&members[0]) => items.pop().expect("one member"),
                1 => format!("({},)", items.pop().expect("one member")),
                _ => format!("({})", items.join(", ")),
            }
        }
        SolType::Struct { .. } => unreachable!("type strings never produce named structs"),
    }
}

fn emit_elements(inner: &SolType, v: &Value) -> Vec<String> {
    v.as_array()
        .expect("array values arrive as a bare JSON list")
        .iter()
        .map(|e| emit_value(inner, e))
        .collect()
}

/// The number of 64-bit limbs `Uint<BITS, LIMBS>` needs.
fn limbs(bits: usize) -> usize {
    bits.div_ceil(64)
}

fn emit_uint(bits: usize, decimal: &str) -> String {
    match bits {
        8 => format!("{decimal}u8"),
        16 => format!("{decimal}u16"),
        32 => format!("{decimal}u32"),
        64 => format!("{decimal}u64"),
        128 => format!("{decimal}u128"),
        _ => format!("uint::<{bits}, {}>({decimal:?})", limbs(bits)),
    }
}

fn emit_int(bits: usize, decimal: &str) -> String {
    match bits {
        8 => format!("{decimal}i8"),
        16 => format!("{decimal}i16"),
        32 => format!("{decimal}i32"),
        64 => format!("{decimal}i64"),
        128 => format!("{decimal}i128"),
        _ => format!("int::<{bits}, {}>({decimal:?})", limbs(bits)),
    }
}

/// Whether a Solidity type is encoded with an offset word rather than in place.
fn is_dynamic(ty: &SolType) -> bool {
    match ty {
        SolType::String | SolType::Bytes | SolType::Array(_) => true,
        SolType::FixedArray(inner, _) => is_dynamic(inner),
        SolType::Tuple(members) => members.iter().any(is_dynamic),
        SolType::Struct { fields, .. } => fields.iter().any(|(_, ty)| is_dynamic(ty)),
        _ => false,
    }
}

/// A canonical spelling of a type, used as the key under which a tuple shape gets its struct name.
fn shape_key(ty: &SolType) -> String {
    match ty {
        SolType::Address => "address".into(),
        SolType::Bool => "bool".into(),
        SolType::String => "string".into(),
        SolType::Bytes => "bytes".into(),
        SolType::Uint(bits) => format!("uint{bits}"),
        SolType::Int(bits) => format!("int{bits}"),
        SolType::FixedBytes(size) => format!("bytes{size}"),
        SolType::Array(inner) => format!("{}[]", shape_key(inner)),
        SolType::FixedArray(inner, n) => format!("{}[{n}]", shape_key(inner)),
        SolType::Tuple(members) => format!(
            "tuple({})",
            members.iter().map(shape_key).collect::<Vec<_>>().join(",")
        ),
        SolType::Struct { .. } => unreachable!("type strings never produce named structs"),
    }
}

/// Every tuple node reachable from `ty`, including nested ones.
fn collect_shapes(ty: &SolType, out: &mut BTreeSet<String>) {
    match ty {
        SolType::Array(inner) | SolType::FixedArray(inner, _) => collect_shapes(inner, out),
        SolType::Tuple(members) => {
            out.insert(shape_key(ty));
            for m in members {
                collect_shapes(m, out);
            }
        }
        _ => {}
    }
}

/// Like `sol_to_rust`, but every tuple becomes the named struct generated for its shape.
fn rust_type_named(ty: &SolType, names: &BTreeMap<String, String>) -> String {
    match ty {
        SolType::Array(inner) => format!("Vec<{}>", rust_type_named(inner, names)),
        SolType::FixedArray(inner, n) => format!("[{}; {n}]", rust_type_named(inner, names)),
        SolType::Tuple(_) => names[&shape_key(ty)].clone(),
        _ => {
            let rust = sol_to_rust(ty).unwrap_or_else(|e| panic!("{ty:?}: {e:?}"));
            quote!(#rust).to_string()
        }
    }
}

/// Like `emit_value`, but builds the named structs rather than anonymous tuples.
fn emit_value_named(ty: &SolType, v: &Value, names: &BTreeMap<String, String>) -> String {
    match ty {
        SolType::Array(inner) => format!(
            "vec![{}]",
            v.as_array()
                .expect("array")
                .iter()
                .map(|e| emit_value_named(inner, e, names))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        SolType::FixedArray(inner, _) => format!(
            "[{}]",
            v.as_array()
                .expect("array")
                .iter()
                .map(|e| emit_value_named(inner, e, names))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        SolType::Tuple(members) => {
            let values = v["value"].as_array().expect("tuple members");
            let fields: Vec<String> = members
                .iter()
                .zip(values)
                .enumerate()
                .map(|(i, (t, e))| format!("f{i}: {}", emit_value_named(t, e, names)))
                .collect();
            format!("{} {{ {} }}", names[&shape_key(ty)], fields.join(", "))
        }
        _ => emit_value(ty, v),
    }
}
