// Generated by gen_tests.js from tests@v20.0.2; do not edit manually.
// Regenerate with: node gen_tests.js

macro_rules! define_tests {
    ($(fn $name:ident($path:literal);)*) => {
        $(#[test] fn $name() { $crate::utils::run_evm_e2e_test($path); })*
    };
}

mod good_coverage_tests {
    mod osaka {
        define_tests! {
            fn case_byzantium_eip196_ec_add_mul_ecadd_valid("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/byzantium/eip196_ec_add_mul/ecadd/valid.json");
            fn case_cancun_eip1153_tstore_tstorage_create_contexts_contract_creation("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/cancun/eip1153_tstore/tstorage_create_contexts/contract_creation.json");
            fn case_constantinople_eip1052_extcodehash_extcodehash_codecopy_zero_in_create2("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/constantinople/eip1052_extcodehash/extcodehash/codecopy_zero_in_create2.json");
            fn case_constantinople_eip1052_extcodehash_extcodehash_extcodehash_call_to_selfdestruct("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/constantinople/eip1052_extcodehash/extcodehash/extcodehash_call_to_selfdestruct.json");
            fn case_frontier_opcodes_call_and_callcode_gas_calculation_value_transfer_gas_calculation("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/frontier/opcodes/call_and_callcode_gas_calculation/value_transfer_gas_calculation.json");
            fn case_frontier_opcodes_extcodecopy_extcodecopy_bounds("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/frontier/opcodes/extcodecopy/extcodecopy_bounds.json");
            fn case_ported_static_stcodecopytest_ext_code_copy_tests_paris_ext_code_copy_tests_paris("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stCodeCopyTest/ext_code_copy_tests_paris/ext_code_copy_tests_paris.json");
            fn case_ported_static_stcreate2_create2_suicide_create2_suicide("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stCreate2/create2_suicide/create2_suicide.json");
            fn case_ported_static_stcreate2_create2collision_selfdestructed_create2collision_selfdestructed("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stCreate2/create2collision_selfdestructed/create2collision_selfdestructed.json");
            fn case_ported_static_stcreatetest_create2_call_data_create2_call_data("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stCreateTest/create2_call_data/create2_call_data.json");
            fn case_ported_static_stcreatetest_create_address_warm_after_fail_create_address_warm_after_fail("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stCreateTest/create_address_warm_after_fail/create_address_warm_after_fail.json");
            fn case_ported_static_stcreatetest_create_fail_result_create_fail_result("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stCreateTest/create_fail_result/create_fail_result.json");
            fn case_ported_static_stcreatetest_create_results_create_results_with_call("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stCreateTest/create_results/create_results_with_call.json");
            fn case_ported_static_stcreatetest_create_results_create_results_without_call("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stCreateTest/create_results/create_results_without_call.json");
            fn case_ported_static_stcreatetest_create_results_returndatacopy_after_successful_create_aborts("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stCreateTest/create_results/returndatacopy_after_successful_create_aborts.json");
            fn case_ported_static_steip1153_transientstorage_14_revert_after_nested_staticcall_14_revert_after_nested_staticcall("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stEIP1153_transientStorage/14_revert_after_nested_staticcall/14_revert_after_nested_staticcall.json");
            fn case_ported_static_steip3651_warmcoinbase_coinbase_warm_account_call_gas_coinbase_warm_account_call_gas("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stEIP3651_warmcoinbase/coinbase_warm_account_call_gas/coinbase_warm_account_call_gas.json");
            fn case_ported_static_steip3651_warmcoinbase_coinbase_warm_account_call_gas_fail_coinbase_warm_account_call_gas_fail("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stEIP3651_warmcoinbase/coinbase_warm_account_call_gas_fail/coinbase_warm_account_call_gas_fail.json");
            fn case_ported_static_steip3855_push0_push0_push0("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stEIP3855_push0/push0/push0.json");
            fn case_ported_static_steip3860_limitmeterinitcode_create_init_code_size_limit_create_init_code_size_limit("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stEIP3860_limitmeterinitcode/create_init_code_size_limit/create_init_code_size_limit.json");
            fn case_ported_static_stinitcodetest_call_contract_to_create_contract_and_call_it_oog_call_contract_to_create_contract_and_call_it_oog("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stInitCodeTest/call_contract_to_create_contract_and_call_it_oog/call_contract_to_create_contract_and_call_it_oog.json");
            fn case_ported_static_stinitcodetest_call_contract_to_create_contract_oog_bonus_gas_call_contract_to_create_contract_oog_bonus_gas("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stInitCodeTest/call_contract_to_create_contract_oog_bonus_gas/call_contract_to_create_contract_oog_bonus_gas.json");
            fn case_ported_static_stinitcodetest_transaction_create_auto_suicide_contract_transaction_create_auto_suicide_contract("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stInitCodeTest/transaction_create_auto_suicide_contract/transaction_create_auto_suicide_contract.json");
            fn case_ported_static_stprecompiledcontracts2_call_ecrecover0_no_gas_call_ecrecover0_no_gas("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stPreCompiledContracts2/call_ecrecover0_no_gas/call_ecrecover0_no_gas.json");
            fn case_ported_static_stprecompiledcontracts2_call_ecrecover1_call_ecrecover1("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stPreCompiledContracts2/call_ecrecover1/call_ecrecover1.json");
            fn case_ported_static_stprecompiledcontracts2_modexp_0_0_0_20500_modexp_0_0_0_20500("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stPreCompiledContracts2/modexp_0_0_0_20500/modexp_0_0_0_20500.json");
            fn case_ported_static_strefundtest_refund_tx_to_suicide_oog_refund_tx_to_suicide_oog("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stRefundTest/refund_tx_to_suicide_oog/refund_tx_to_suicide_oog.json");
            fn case_ported_static_streturndatatest_call_outsize_then_create_successful_then_returndatasize_call_outsize_then_create_successful_then_returndatasize("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stReturnDataTest/call_outsize_then_create_successful_then_returndatasize/call_outsize_then_create_successful_then_returndatasize.json");
            fn case_ported_static_streturndatatest_call_then_create_successful_then_returndatasize_call_then_create_successful_then_returndatasize("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stReturnDataTest/call_then_create_successful_then_returndatasize/call_then_create_successful_then_returndatasize.json");
            fn case_ported_static_streturndatatest_revert_ret_data_size_revert_ret_data_size("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stReturnDataTest/revert_ret_data_size/revert_ret_data_size.json");
            fn case_ported_static_stsstoretest_sstore_call_to_self_sub_refund_below_zero_sstore_call_to_self_sub_refund_below_zero("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stSStoreTest/sstore_call_to_self_sub_refund_below_zero/sstore_call_to_self_sub_refund_below_zero.json");
            fn case_ported_static_stsstoretest_sstore_change_from_external_call_in_init_code_sstore_change_from_external_call_in_init_code("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stSStoreTest/sstore_change_from_external_call_in_init_code/sstore_change_from_external_call_in_init_code.json");
            fn case_ported_static_stsstoretest_sstore_gas_sstore_gas("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stSStoreTest/sstore_gas/sstore_gas.json");
            fn case_ported_static_stspecialtest_selfdestruct_eip2929_selfdestruct_eip2929("tests/ethereum-tests-v20.0.2-osaka/state_tests/for_osaka/ported_static/stSpecialTest/selfdestruct_eip2929/selfdestruct_eip2929.json");
        }
    }
}
