// Generate current Ethereum state-test registrations. Run after `make sync_tests`.
// `node gen_tests.js --check` verifies the registrations without changing files.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const config = JSON.parse(fs.readFileSync(path.join(root, 'ethereum-tests.json')));
const selection = JSON.parse(fs.readFileSync(path.join(root, 'ci-tests.json')));
const exclusions = new Map();
for (const entry of JSON.parse(fs.readFileSync(path.join(root, 'excluded-tests.json')))) {
    const key = `${entry.fork}/${entry.path}`;
    if (!config.forks.includes(entry.fork) || typeof entry.path !== 'string' ||
        typeof entry.reason !== 'string' || !entry.reason.trim() ||
        typeof entry.source !== 'string' || !entry.source.trim()) {
        throw new Error(`Exclusions require a supported fork, path, reason and source: ${key}`);
    }
    for (const field of ['cases', 'exceptions']) {
        if (entry[field] !== undefined && (!Array.isArray(entry[field]) || !entry[field].length ||
            entry[field].some(value => typeof value !== 'string' || !value))) {
            throw new Error(`Invalid ${field} selector: ${key}`);
        }
    }
    if (exclusions.has(key)) throw new Error(`Duplicate exclusion: ${key}`);
    exclusions.set(key, entry);
}
const unmatchedExclusions = new Set(exclusions.keys());
const base = path.join(root, config.directory, 'state_tests');
const header = `// Generated by gen_tests.js from ${config.release}; do not edit manually.
// Regenerate with: node gen_tests.js

macro_rules! define_tests {
    ($($(#[$meta:meta])* fn $name:ident($path:literal);)*) => {
        $($(#[$meta])* #[test] fn $name() { $crate::utils::run_evm_e2e_test($path); })*
    };
}
`;

function jsonFiles(directory) {
    return fs.readdirSync(directory, {withFileTypes: true}).flatMap(entry => {
        const target = path.join(directory, entry.name);
        if (entry.isDirectory()) return jsonFiles(target);
        return entry.isFile() && entry.name.endsWith('.json') ? [target] : [];
    }).sort();
}

function identifier(value) {
    return `case_${value.replace(/[^A-Za-z0-9]/g, '_').toLowerCase()}`;
}

function excluded(entry, name, post) {
    return entry && (!entry.cases || entry.cases.includes(name)) &&
        (!entry.exceptions || (post.expectException || '').split('|').some(value => entry.exceptions.includes(value)));
}

let full = header;
let ci = header + '\nmod good_coverage_tests {\n';
let total = 0;
let ciTotal = 0;
let excludedCases = 0;
let ignoredFiles = 0;
for (const fork of config.forks) {
    const selected = new Set(selection.filter(entry => entry.forks.includes(fork)).map(entry => entry.path));
    const directory = path.join(base, `for_${fork.toLowerCase()}`);
    const found = new Set();
    const names = new Set();
    full += `\nmod ${fork.toLowerCase()} {\n    define_tests! {\n`;
    ci += `    mod ${fork.toLowerCase()} {\n        define_tests! {\n`;
    for (const file of jsonFiles(directory)) {
        const relative = path.relative(directory, file).split(path.sep).join('/');
        const name = identifier(relative.replace(/\.json$/, ''));
        if (names.has(name)) throw new Error(`Duplicate Rust test identifier: ${name}`);
        names.add(name);
        const suite = JSON.parse(fs.readFileSync(file));
        const cases = Object.values(suite).reduce((sum, unit) => sum + (unit.post?.[fork]?.length ?? 0), 0);
        if (!cases) throw new Error(`No ${fork} transactions in ${relative}`);
        const testPath = path.relative(root, file).split(path.sep).join('/');
        const line = `fn ${name}(${JSON.stringify(testPath)});`;
        const exclusionKey = `${fork}/${relative}`;
        const exclusion = exclusions.get(exclusionKey);
        if (exclusion) {
            if (selected.has(relative)) throw new Error(`CI fixture is excluded: ${relative}`);
            const excludedCount = Object.entries(suite).reduce((sum, [name, unit]) =>
                sum + (unit.post?.[fork] || []).filter(post => excluded(exclusion, name, post)).length, 0);
            if (!excludedCount) throw new Error(`Stale exclusion selector: ${exclusionKey}`);
            if (exclusion.cases && exclusion.cases.some(name => !(name in suite))) {
                throw new Error(`Stale excluded case: ${exclusionKey}`);
            }
            unmatchedExclusions.delete(exclusionKey);
            if (excludedCount === cases) {
                full += `        #[ignore = ${JSON.stringify(exclusion.reason)}]\n`;
                ignoredFiles += 1;
            }
            excludedCases += excludedCount;
        }
        full += `        ${line}\n`;
        total += cases;
        if (selected.has(relative)) {
            ci += `            ${line}\n`;
            found.add(relative);
            ciTotal += cases;
        }
    }
    for (const required of selected) {
        if (!found.has(required)) throw new Error(`Missing CI fixture for ${fork}: ${required}`);
    }
    full += '    }\n}\n';
    ci += '        }\n    }\n';
}
ci += '}\n';
if (!total || !ciTotal) throw new Error('The fixture selection contains no transactions');
if (unmatchedExclusions.size) throw new Error(`Stale exclusions: ${[...unmatchedExclusions].join(', ')}`);
for (const [filename, output] of [['tests.rs', full], ['short_tests.rs', ci]]) {
    const target = path.join(root, 'src', filename);
    if (process.argv.includes('--check')) {
        if (fs.readFileSync(target, 'utf8') !== output) throw new Error(`${filename} is stale; run node gen_tests.js`);
    } else {
        fs.writeFileSync(target, output);
    }
}
console.log(`${config.release}: ${total} registered transaction cases; ${excludedCases} explicitly excluded (${ignoredFiles} whole files, ${exclusions.size - ignoredFiles} partial files); ${ciTotal} in CI (${selection.length} fixture families)`);
