use crate::SysFuncIdx::SYS_STATE;
use crate::{create_sovereign_import_linker, ExitCode, STATE_DEPLOY, STATE_MAIN};
use alloc::boxed::Box;
use alloc::string::ToString;
use alloc::vec;
use alloc::vec::Vec;
use rwasm::engine::bytecode::Instruction;
use rwasm::engine::{RwasmConfig, StateRouterConfig};
use rwasm::rwasm::{BinaryFormat, BinaryFormatWriter, RwasmModule};
use rwasm::Error;
