// SPDX-License-Identifier: MIT
// This file is auto-generated
// DO NOT EDIT THIS FILE MANUALLY!
// Source contract: RouterApi

pragma solidity ^0.8.0;

interface IRouterApi {

    function greeting(string calldata message) external view returns (string calldata return_0);
    function customGreeting(string calldata message) external view returns (string calldata return_0);
}