[package]
name = "fluentbase-precompile-crypto"
version.workspace = true
description.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
fluentbase-types = { workspace = true }
fluentbase-crypto = { workspace = true }
revm-precompile = { workspace = true }

[features]
default = ["std"]
std = [
    "fluentbase-types/std",
    "fluentbase-crypto/std",
    "revm-precompile/std",
]
