name: Release (Genesis & Fluent)

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Enable dry run mode (builds artifacts but skips uploads and release creation)"
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  REPO_NAME: ${{ github.repository_owner }}/fluent
  IMAGE_NAME: ${{ github.repository_owner }}/fluent
  DOCKER_IMAGE_NAME_URL: https://ghcr.io/${{ github.repository_owner }}/fluent
  RUSTC_WRAPPER: "sccache"

jobs:
  dry-run:
    name: check dry run
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Dry run value: ${{ github.event.inputs.dry_run }}"
          echo "Dry run enabled: ${{ github.event.inputs.dry_run == 'true'}}"
          echo "Dry run disabled: ${{ github.event.inputs.dry_run != 'true'}}"

  extract-version:
    name: extract version
    runs-on: ubuntu-amd64-8core
    steps:
      - name: Extract and sanitize version
        id: extract_version
        run: |
          VERSION="${GITHUB_REF_NAME}"
          # Replace slashes with dashes (safe for filenames)
          VERSION="${VERSION//\//-}"
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
    outputs:
      VERSION: ${{ steps.extract_version.outputs.VERSION }}

  check-version:
    name: check version
    runs-on: ubuntu-amd64-8core
    needs: extract-version
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: Verify crate version matches tag
        # Check that the Cargo version starts with the tag,
        # so that Cargo version 1.4.8 can be matched against both v1.4.8 and v1.4.8-rc.1
        run: |
          tag="${{ needs.extract-version.outputs.VERSION }}"
          tag=${tag#v}
          cargo_ver=$(grep -m1 '^version' Cargo.toml | awk -F'=' '{print $2}' | tr -d ' "')
          [[ "$tag" == "$cargo_ver"* ]] || { echo "Tag $tag doesn’t match the Cargo version $cargo_ver"; exit 1; }

  build-genesis:
    name: build genesis
    runs-on: ubuntu-amd64-8core
    needs: extract-version
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown
      - name: Build Genesis
        run: cargo b --release

      - name: Package genesis files
        run: |
          mkdir -p artifacts
          gzip -c ./crates/genesis/genesis-devnet.json > ./artifacts/genesis-${{ needs.extract-version.outputs.VERSION }}.json.gz
          gzip -c ./crates/genesis/genesis-mainnet.json > ./artifacts/genesis-mainnet-${{ needs.extract-version.outputs.VERSION }}.json.gz

      - name: Configure GPG and sign genesis artifacts
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          export GPG_TTY=$(tty)
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --batch --import
          cd artifacts
          echo "$GPG_PASSPHRASE" | gpg --passphrase-fd 0 --pinentry-mode loopback --batch -ab genesis-${{ needs.extract-version.outputs.VERSION }}.json.gz
          echo "$GPG_PASSPHRASE" | gpg --passphrase-fd 0 --pinentry-mode loopback --batch -ab genesis-mainnet-${{ needs.extract-version.outputs.VERSION }}.json.gz
          mv * ..

      - name: Upload devnet genesis
        if: ${{ github.event.inputs.dry_run != 'true' }}
        uses: actions/upload-artifact@v7
        with:
          name: genesis-${{ needs.extract-version.outputs.VERSION }}.json.gz
          path: genesis-${{ needs.extract-version.outputs.VERSION }}.json.gz

      - name: Upload mainnet genesis
        if: ${{ github.event.inputs.dry_run != 'true' }}
        uses: actions/upload-artifact@v7
        with:
          name: genesis-mainnet-${{ needs.extract-version.outputs.VERSION }}.json.gz
          path: genesis-mainnet-${{ needs.extract-version.outputs.VERSION }}.json.gz

      - name: Upload devnet genesis signature
        if: ${{ github.event.inputs.dry_run != 'true' }}
        uses: actions/upload-artifact@v7
        with:
          name: genesis-${{ needs.extract-version.outputs.VERSION }}.json.gz.asc
          path: genesis-${{ needs.extract-version.outputs.VERSION }}.json.gz.asc

      - name: Upload mainnet genesis signature
        if: ${{ github.event.inputs.dry_run != 'true' }}
        uses: actions/upload-artifact@v7
        with:
          name: genesis-mainnet-${{ needs.extract-version.outputs.VERSION }}.json.gz.asc
          path: genesis-mainnet-${{ needs.extract-version.outputs.VERSION }}.json.gz.asc

  build:
    name: build release
    runs-on: ${{ matrix.configs.os }}
    needs: extract-version
    continue-on-error: ${{ matrix.configs.allow_fail }}
    strategy:
      fail-fast: true
      matrix:
        configs:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-amd64-8core
            profile: maxperf
            allow_fail: false
        #  - target: x86_64-apple-darwin
        #    os: macos-14
        #    profile: maxperf
        #    allow_fail: false
        #  - target: aarch64-apple-darwin
        #    os: macos-14
        #    profile: maxperf
        #    allow_fail: false
        #  - target: x86_64-pc-windows-gnu
        #    os: ubuntu-24.04
        #    profile: maxperf
        #    allow_fail: false
        #  - target: riscv64gc-unknown-linux-gnu
        #    os: ubuntu-24.04
        #    profile: maxperf
        #    allow_fail: true
        build:
          - command: build
            binary: fluent
            artifact_binary: fluent
            features: >-
              wasmtime,jemalloc,otlp,otlp-logs,reth-revm/portable,js-tracer,
              keccak-cache-global,asm-keccak,min-debug-logs,rocksdb
          - command: build
            binary: fluent
            artifact_binary: fluent-rwasm
            features: >-
              jemalloc,otlp,otlp-logs,reth-revm/portable,js-tracer,
              keccak-cache-global,asm-keccak,min-debug-logs,rocksdb
    steps:
      - uses: actions/checkout@v6
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.configs.target }}
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: Install cross main
        id: cross_main
        run: |
          cargo +1.92.0 install cross --git https://github.com/cross-rs/cross
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Apple M1 setup
        if: matrix.configs.target == 'aarch64-apple-darwin'
        run: |
          echo "SDKROOT=$(xcrun -sdk macosx --show-sdk-path)" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx --show-sdk-platform-version)" >> $GITHUB_ENV
      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Build Fluent
        env:
          BUILD_FEATURES: ${{ matrix.build.features }}
        run: make PROFILE=${{ matrix.configs.profile }} FEATURES="$BUILD_FEATURES" NO_DEFAULT_FEATURES="--no-default-features" ${{ matrix.build.command }}-${{ matrix.configs.target }}

      - name: Move binary
        run: |
          mkdir -p artifacts
          cp "target/${{ matrix.configs.target }}/${{ matrix.configs.profile }}/${{ matrix.build.binary }}" "./artifacts/${{ matrix.build.artifact_binary }}"

      - name: Configure GPG and create artifacts
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          export GPG_TTY=$(tty)
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --batch --import
          cd artifacts
          tar -czf ${{ matrix.build.artifact_binary }}-${{ needs.extract-version.outputs.VERSION }}-${{ matrix.configs.target }}.tar.gz ${{ matrix.build.artifact_binary }}
          echo "$GPG_PASSPHRASE" | gpg --passphrase-fd 0 --pinentry-mode loopback --batch -ab ${{ matrix.build.artifact_binary }}-${{ needs.extract-version.outputs.VERSION }}-${{ matrix.configs.target }}.tar.gz
          mv *tar.gz* ..

      - name: Upload fluent
        if: ${{ github.event.inputs.dry_run != 'true' }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.build.artifact_binary }}-${{ needs.extract-version.outputs.VERSION }}-${{ matrix.configs.target }}.tar.gz
          path: ${{ matrix.build.artifact_binary }}-${{ needs.extract-version.outputs.VERSION }}-${{ matrix.configs.target }}.tar.gz

      - name: Upload fluent signature
        if: ${{ github.event.inputs.dry_run != 'true' }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.build.artifact_binary }}-${{ needs.extract-version.outputs.VERSION }}-${{ matrix.configs.target }}.tar.gz.asc
          path: ${{ matrix.build.artifact_binary }}-${{ needs.extract-version.outputs.VERSION }}-${{ matrix.configs.target }}.tar.gz.asc

  draft-release:
    name: draft release
    needs: [ build, build-genesis, extract-version ]
    if: ${{ github.event.inputs.dry_run != 'true' }}
    runs-on: ubuntu-amd64-8core
    env:
      VERSION: ${{ needs.extract-version.outputs.VERSION }}
    permissions:
      # Required to post the release
      contents: write
    steps:
      # This is necessary for generating the changelog.
      # It has to come before "Download Artifacts" or else it deletes the artifacts.
      - uses: actions/checkout@v6
      - name: Download artifacts
        uses: actions/download-artifact@v8
      - name: Generate full changelog
        id: changelog
        run: |
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$(git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 ${{ env.VERSION }}^)..${{ env.VERSION }})" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create release draft
        env:
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # The formatting here is borrowed from Lighthouse (which is borrowed from OpenEthereum):
        # https://github.com/openethereum/openethereum/blob/6c2d392d867b058ff867c4373e40850ca3f96969/.github/workflows/build.yml
        run: |
          prerelease_flag=""
          if [[ "${GITHUB_REF}" == *-rc* ]]; then
            prerelease_flag="--prerelease"
          fi

          body=$(cat <<- "ENDBODY"
          Add a summary, including:

          - Critical bug fixes
          - New features
          - Any breaking changes (and what to expect)

          ## All Changes

          ${{ steps.changelog.outputs.CHANGELOG }}

          ENDBODY
          )
          assets=()
          for d in ./*fluent-*.tar.gz*; do
            assets+=("$d/$(basename "$d")")
          done
          for d in ./*genesis-*.json.gz*; do
            assets+=("$d/$(basename "$d")")
          done
          tag_name="${{ env.VERSION }}"
          echo "$body" | gh release create --draft $prerelease_flag -t "Genesis $tag_name" -F "-" "$tag_name" "${assets[@]}"